config/routes.rb
Buffset::Application.routes.draw do
  match "/signin" => "services#signin"
  match "/signout" => "services#signout"

  match '/auth/:service/callback' => 'services#create'
  match '/auth/failure' => 'services#failure'
  match '/chart' => 'chart#index'
  match '/chart/sum' => 'chart#sum'
  match '/chart/punch' => 'chart#punch'

  resources :services, :only => [:index, :create, :destroy] do
    collection do
      get 'signin'
      get 'signout'
      get 'signup'
      post 'newaccount'
      get 'failure'
    end
  end

  resources :users, :only => [:index, :show, :edit, :update]

  namespace :admin do
    resources :users, :only => [:index, :update]
  end

  root :to => "services#signin"
end

app/views/layouts/admin.html.haml
!!!
%html
  %head
    %title Buffset Admin
    - if Rails.env == 'production'
      %link{:href => 'http://fonts.googleapis.com/css?family=Walter+Turncoat&v2', :rel => 'stylesheet', :type => 'text/css'}
    = javascript_include_tag 'jquery'
    = csrf_meta_tag
  %body
    %section#body
      %nav#nav_user
        %ul
          - if user_signed_in?
            - if current_user.admin?
              %li
                = User.active.count
                active
                \/
                = User.count
                total
            %li= link_to current_user.email, edit_user_path(current_user)
            %li= link_to "Sign out", signout_services_path
          - else
            %li= link_to "Sign in", '/auth/google'
          %li &nbsp;
      .clear
      %section#flash
        - flash.each do |key, value|
          .flash.round{:class => key}
            = value
      = yield
    %script
      = yield :page_javascript

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title Buffset
    %link{:href => 'https://fonts.googleapis.com/css?family=Walter+Turncoat&v2', :rel => 'stylesheet', :type => 'text/css'}
    = stylesheet_link_tag "bootstrap-1.0.0.min", "application"
    = javascript_include_tag 'jquery', 'highcharts/highcharts.src', 'chart'
    = csrf_meta_tag
  %body
    .topbar
      .container.fixed
        %h3
          = link_to "Tapjoy Buffset \\m/", root_path, :class => 'logo'
        %ul.nav
          %li= link_to 'Board', users_path
        %ul.nav
          %li.menu
            = link_to 'Chart', '#', :class => 'menu'
            %ul.menu-dropdown
              %li= link_to 'Competitive', chart_path
              %li= link_to 'Cumulative', chart_sum_path
              %li= link_to 'Punch-card', chart_punch_path
        %ul.nav.secondary-nav
          = yield :nav_links
          - if user_signed_in?
            - if current_user.admin?
              %li= link_to "#{User.active.count} active / #{User.count} total", admin_users_path
            %li.menu
              = link_to current_user.email, '#', :class => 'menu'
              %ul.menu-dropdown
                %li= link_to 'Edit profile', edit_user_path(current_user)
                %li= link_to 'Sign out', signout_services_path
          - else
            %li= link_to "Sign in", '/auth/google'
    .container{:style => 'height: 40px;'}
    .container
      %section#alerts
        - flash.each do |key, value|
          .alert-message{:class => key}
            = link_to "&times;".html_safe, '#', :class => "close"
            = value
    .container#body
      #season-number-outside
        #season-number 2
      = yield
    %script
      = yield :page_javascript
      :plain
        $('li.menu').click(function(e){
          if (e.srcElement.className) {
            $(this).children('ul.menu-dropdown').toggle();
            return false;
          }
        });
        $('.close').click(function(){
          $(this).parent().slideUp();
          return false;
        });